export declare const URL_FULL = "URL_FULL";
export declare const URL_PATH = "URL_PATH";
export declare const URL_DATA = "URL_DATA";
export declare const URL_DOMN = "URL_DOMN";
export declare const URL_SUBD = "URL_SUBD";
export declare const URL_QERY = "URL_QERY";
export declare const URL_HASH = "URL_HASH";
export declare const URL_PAGE = "URL_PAGE";
export declare const URL_PRSE = "unfurl";
export declare const URL_NPRS = "urlify";
export declare const URL: {
    FULL: string;
    PATH: string;
    DATA: string;
    DOMN: string;
    SUBD: string;
    QERY: string;
    HASH: string;
    PAGE: string;
    PRSE: string;
    NPRS: string;
};
export declare const DOM_NODE = "DOM_NODE";
export declare const DOM_BODY = "DOM_BODY";
export declare const DOM_HEAD = "DOM_HEAD";
export declare const DOM: {
    NODE: string;
    BODY: string;
    HEAD: string;
};
export declare const HD_TITL = "title";
export declare const HD_ICON = "favicon";
export declare const HD_META = "meta";
export declare const OG_DESC = "og_description";
export declare const OG_IMGU = "og_image";
export declare const OG_IMGW = "og_image_width";
export declare const OG_IMGH = "og_image_height";
export declare const OG_TYPE = "og_type";
export declare const STATE_PATH = "STE_PATH";
export declare const STATE_DATA = "STE_DATA";
export declare const STATE: {
    PATH: string;
    DATA: string;
};
export declare const CMD_SUB$ = "sub$";
export declare const CMD_ARGS = "args";
export declare const CMD_RESO = "reso";
export declare const CMD_ERRO = "erro";
export declare const CMD_WORK = "work";
export declare const CMD_SRC$ = "src$";
export declare const CMD: {
    SUB$: string;
    ARGS: string;
    RESO: string;
    ERRO: string;
    WORK: string;
    SRC$: string;
};
export declare const CFG_RUN$ = "run";
export declare const CFG_STOR = "state";
export declare const CFG_ROOT = "CFG_ROOT";
export declare const CFG_VIEW = "CFG_VIEW";
export declare const CFG_KICK = "CFG_KICK";
export declare const CFG_DRFT = "CFG_DRFT";
export declare const CFG_LOG$ = "CFG_LOG$";
export declare const CFG_RUTR = "CFG_RUTR";
export declare const CFG: {
    RUN$: string;
    STOR: string;
    ROOT: string;
    VIEW: string;
    DRFT: string;
    LOG$: string;
    RUTR: string;
    KICK: string;
};
export declare const RTR_PREP = "RTR_PREP";
export declare const RTR_POST = "RTR_POST";
export declare const RTR_PRFX = "RTR_PRFX";
export declare const RTR: {
    PREP: string;
    POST: string;
    PRFX: string;
    RUTR: string;
};
export declare const $$_PATH = "$$_PATH";
export declare const $$_LOAD = "$$_LOAD";
export declare const $$_VIEW = "$$_VIEW";
export declare const $$_ROOT = "$$_ROOT";
export declare const $$: Object;
export declare const $$_DEFAULT: {
    $$_PATH: any[];
    $$_LOAD: boolean;
    $$_VIEW: any;
    $$_ROOT: any;
};
